//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroAdventureCreator.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetroAdventureCreator.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument message serialized is required.
        /// </summary>
        internal static string ArgumentMessageSerializedRequired {
            get {
                return ResourceManager.GetString("ArgumentMessageSerializedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument vocabulary serialized is required.
        /// </summary>
        internal static string ArgumentVocabularySerializedRequired {
            get {
                return ResourceManager.GetString("ArgumentVocabularySerializedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code property is required.
        /// </summary>
        internal static string CodeIsRequiredError {
            get {
                return ResourceManager.GetString("CodeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands property are required.
        /// </summary>
        internal static string CommandsAreRequired {
            get {
                return ResourceManager.GetString("CommandsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description property in {0} is required.
        /// </summary>
        internal static string DescriptionIsRequiredError {
            get {
                return ResourceManager.GetString("DescriptionIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code &apos;{0}&apos; is duplicated, code property should be unique in game parts..
        /// </summary>
        internal static string DuplicateCodeError {
            get {
                return ResourceManager.GetString("DuplicateCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownoer Code &apos;{0}&apos; is duplicated, owner code property should be unique in game parts..
        /// </summary>
        internal static string DuplicatedOwnerCodeError {
            get {
                return ResourceManager.GetString("DuplicatedOwnerCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input command verb is required.
        /// </summary>
        internal static string InputCommandVerbIsRequired {
            get {
                return ResourceManager.GetString("InputCommandVerbIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of actors allowed is {0}.
        /// </summary>
        internal static string MaxLengthActorsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthActorsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of after input command dispatchers allowed is {0}.
        /// </summary>
        internal static string MaxLengthAfterInputCommandDispatchersAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthAfterInputCommandDispatchersAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of before input command dispatchers allowed is {0}.
        /// </summary>
        internal static string MaxLengthBeforeInputCommandDispatchersAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthBeforeInputCommandDispatchersAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of child object is {0}.
        /// </summary>
        internal static string MaxLengthChildObjectsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthChildObjectsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of command arguments is {0}.
        /// </summary>
        internal static string MaxLengthCommandArgumentsError {
            get {
                return ResourceManager.GetString("MaxLengthCommandArgumentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of commands allowed is {0}.
        /// </summary>
        internal static string MaxLengthCommandsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthCommandsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of flags allowed is {0}.
        /// </summary>
        internal static string MaxLengthFlagsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthFlagsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the maximum length of ids is {0}.
        /// </summary>
        internal static string MaxLengthIdsError {
            get {
                return ResourceManager.GetString("MaxLengthIdsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of input commands allowed is {0}.
        /// </summary>
        internal static string MaxLengthInputCommandsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthInputCommandsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of input commands nouns allowed is {0}.
        /// </summary>
        internal static string MaxLengthInputCommandsNounsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthInputCommandsNounsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of messages allowed is {0}.
        /// </summary>
        internal static string MaxLengthMessagesAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthMessagesAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of text is {0}.
        /// </summary>
        internal static string MaxLengthMessageTextError {
            get {
                return ResourceManager.GetString("MaxLengthMessageTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of object health is {0}.
        /// </summary>
        internal static string MaxLengthObjectHealthError {
            get {
                return ResourceManager.GetString("MaxLengthObjectHealthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of objects allowed is {0}.
        /// </summary>
        internal static string MaxLengthObjectsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthObjectsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of object weight is {0}.
        /// </summary>
        internal static string MaxLengthObjectWeightError {
            get {
                return ResourceManager.GetString("MaxLengthObjectWeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of player experience points is {0}.
        /// </summary>
        internal static string MaxLengthPlayerExperiencePointsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthPlayerExperiencePointsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of player health is {0}.
        /// </summary>
        internal static string MaxLengthPlayerHealthAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthPlayerHealthAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of player objects allowed is {0}.
        /// </summary>
        internal static string MaxLengthPlayerObjectsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthPlayerObjectsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of scenes allowed is {0}.
        /// </summary>
        internal static string MaxLengthScenesAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthScenesAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of vocabularies nouns allowed is {0}.
        /// </summary>
        internal static string MaxLengthVocabularyNounsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthVocabularyNounsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum size of synonyms is {0}.
        /// </summary>
        internal static string MaxLengthVocabularySynonymsError {
            get {
                return ResourceManager.GetString("MaxLengthVocabularySynonymsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of vocabulary verbs is {0}.
        /// </summary>
        internal static string MaxLengthVocabularyVerbsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthVocabularyVerbsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceded maximum (16 bits) pointer length for store component {0}. Reduce number of components..
        /// </summary>
        internal static string MaxPointerExceededError {
            get {
                return ResourceManager.GetString("MaxPointerExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property in {0} is required.
        /// </summary>
        internal static string NameIsRequiredError {
            get {
                return ResourceManager.GetString("NameIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner property is required in {0}.
        /// </summary>
        internal static string OwnerIsRequiredError {
            get {
                return ResourceManager.GetString("OwnerIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms property is required.
        /// </summary>
        internal static string SysnonymsAreRequiredError {
            get {
                return ResourceManager.GetString("SysnonymsAreRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text property is required.
        /// </summary>
        internal static string TextIsRequiredError {
            get {
                return ResourceManager.GetString("TextIsRequiredError", resourceCulture);
            }
        }
    }
}
