//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroAdventureCreator.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetroAdventureCreator.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code property is required.
        /// </summary>
        internal static string CodeIsRequiredError {
            get {
                return ResourceManager.GetString("CodeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code &apos;{0}&apos; is duplicated, code property should be unique in game parts..
        /// </summary>
        internal static string DuplicateCodeError {
            get {
                return ResourceManager.GetString("DuplicateCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of commands allowed is {0}.
        /// </summary>
        internal static string MaxNumberCommandsAllowedError {
            get {
                return ResourceManager.GetString("MaxNumberCommandsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of messages allowed is {0}.
        /// </summary>
        internal static string MaxNumberMessagesAllowedError {
            get {
                return ResourceManager.GetString("MaxNumberMessagesAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of vocabularies allowed is {0}.
        /// </summary>
        internal static string MaxNumberVocabularyAllowedError {
            get {
                return ResourceManager.GetString("MaxNumberVocabularyAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum size of command arguments is {0}.
        /// </summary>
        internal static string MaxSizeOfCommandArgumentsError {
            get {
                return ResourceManager.GetString("MaxSizeOfCommandArgumentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum size of synonys is {0}.
        /// </summary>
        internal static string MaxSizeOfSynonymsError {
            get {
                return ResourceManager.GetString("MaxSizeOfSynonymsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text property is required.
        /// </summary>
        internal static string TextIsRequiredError {
            get {
                return ResourceManager.GetString("TextIsRequiredError", resourceCulture);
            }
        }
    }
}
