//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroAdventureCreator.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetroAdventureCreator.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument message serialized is required.
        /// </summary>
        internal static string ArgumentMessageSerializedRequired {
            get {
                return ResourceManager.GetString("ArgumentMessageSerializedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument vocabulary serialized is required.
        /// </summary>
        internal static string ArgumentVocabularySerializedRequired {
            get {
                return ResourceManager.GetString("ArgumentVocabularySerializedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code property is required.
        /// </summary>
        internal static string CodeIsRequiredError {
            get {
                return ResourceManager.GetString("CodeIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description property is required.
        /// </summary>
        internal static string DescriptionIsRequiredError {
            get {
                return ResourceManager.GetString("DescriptionIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code &apos;{0}&apos; is duplicated, code property should be unique in game parts..
        /// </summary>
        internal static string DuplicateCodeError {
            get {
                return ResourceManager.GetString("DuplicateCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input command verb is required.
        /// </summary>
        internal static string InputCommandVerbIsRequired {
            get {
                return ResourceManager.GetString("InputCommandVerbIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of child object is {0}.
        /// </summary>
        internal static string MaxLengthChildObjectsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthChildObjectsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of command arguments is {0}.
        /// </summary>
        internal static string MaxLengthCommandArgumentsError {
            get {
                return ResourceManager.GetString("MaxLengthCommandArgumentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of commands allowed is {0}.
        /// </summary>
        internal static string MaxLengthCommandsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthCommandsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of object complements is {0}.
        /// </summary>
        internal static string MaxLengthComplementsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthComplementsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of input commands allowed is {0}.
        /// </summary>
        internal static string MaxLengthInputCommandsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthInputCommandsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of input commands nouns allowed is {0}.
        /// </summary>
        internal static string MaxLengthInputCommandsNounsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthInputCommandsNounsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of messages allowed is {0}.
        /// </summary>
        internal static string MaxLengthMessagesAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthMessagesAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of text is {0}.
        /// </summary>
        internal static string MaxLengthMessageTextError {
            get {
                return ResourceManager.GetString("MaxLengthMessageTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of object health is {0}.
        /// </summary>
        internal static string MaxLengthObjectHealthError {
            get {
                return ResourceManager.GetString("MaxLengthObjectHealthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of objects allowed is {0}.
        /// </summary>
        internal static string MaxLengthObjectsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthObjectsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of object weight is {0}.
        /// </summary>
        internal static string MaxLengthObjectWeightError {
            get {
                return ResourceManager.GetString("MaxLengthObjectWeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of objects required complements is {0}.
        /// </summary>
        internal static string MaxLengthRequiredComplementsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthRequiredComplementsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of vocabularies allowed is {0}.
        /// </summary>
        internal static string MaxLengthVocabularyAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthVocabularyAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum size of synonyms is {0}.
        /// </summary>
        internal static string MaxLengthVocabularySynonymsError {
            get {
                return ResourceManager.GetString("MaxLengthVocabularySynonymsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of vocabulary verbs is {0}.
        /// </summary>
        internal static string MaxLengthVocabularyVerbsAllowedError {
            get {
                return ResourceManager.GetString("MaxLengthVocabularyVerbsAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is required.
        /// </summary>
        internal static string NameIsRequiredError {
            get {
                return ResourceManager.GetString("NameIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms property is required.
        /// </summary>
        internal static string SysnonymsAreRequiredError {
            get {
                return ResourceManager.GetString("SysnonymsAreRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text property is required.
        /// </summary>
        internal static string TextIsRequiredError {
            get {
                return ResourceManager.GetString("TextIsRequiredError", resourceCulture);
            }
        }
    }
}
